### ISSUE TITLE
The Action seems to fail on macOS

### ISSUE THREAD

**Issue by radeusgd** [ayltai/setup-graalvm#2]
**Describe the bug**
The action fails with insufficient permissions on macOS.

**To Reproduce**
1. Create a GitHub Actions workflow with a job that contains a following step:
```
- name: Setup GraalVM Environment
  uses: ayltai/setup-graalvm@v1
  with:
    graalvm-version: 20.1.0
    java-version: 11
    native-image: true
```
that runs on `macOS-latest`.

**Expected behavior**
The action succeeds and prepares an environment with GraalVM. Like it does on Linux and Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/1436948/88051491-fbc87380-cb58-11ea-8be0-88a5cd28eaec.png)
